### ISSUE TITLE
AttributeError: 'Core' object has no attribute 'return_path'

### ISSUE THREAD

**Issue by sugizo** [EchterAlsFake/xvideos_api#4]
**step**
`pip install git+https://github.com/EchterAlsFake/xvideos_api`

**execute**
```
!xvideos_api \
    --download 'https://www.xvideos.com/video.kkeilcbaf66/milf_and_step_son_school_art_project_4k_mandy_flores' \
    --quality 'best' \
    --downloader 'threaded' \
    --use-title True \
    --output 'milf_and_step_son_school_art_project_4k_mandy_flores.mp4'
```

**result**
```
Traceback (most recent call last):
  File "/usr/local/bin/xvideos_api", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/xvideos_api/xvideos_api.py", line 318, in main
    path = Core().return_path(args=args, video=video)
AttributeError: 'Core' object has no attribute 'return_path'
```

**and execute**
`!xvideos_api --file 'urls.txt' --quality 'best' --downloader 'threaded' --use-title True --output './'`

**result**
```
Traceback (most recent call last):
  File "/usr/local/bin/xvideos_api", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/xvideos_api/xvideos_api.py", line 332, in main
    path = Core().return_path(args=args, video=video)
AttributeError: 'Core' object has no attribute 'return_path'
```

best regards

**Comment by EchterAlsFake** [comment]
You need to update the eaf_base_api from git. Haven't pushed a Pypi release yet.

`pip install --upgrade git+https://github.com/echteralsfake/eaf_base_api`
