### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by sugizo** [EchterAlsFake/xvideos_api#5]
**steps**
```
pip install git+https://github.com/EchterAlsFake/xvideos_api
pip install -U eaf_base_api # # not work same result
pip install -U git+https://github.com/echteralsfake/eaf_base_api # not work same result
```

**execute**
```
!xvideos_api \
    --download 'https://www.xvideos.com/video.kkeilcbaf66/milf_and_step_son_school_art_project_4k_mandy_flores' \
    --quality 'best' \
    --downloader 'threaded' \
    --use-title True \
    --output './' \
    --output 'milf_and_step_son_school_art_project_4k_mandy_flores.mp4'
```

**result**
```
[##################################################] 100.0%Traceback (most recent call last):
  File "/usr/local/bin/xvideos_api", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/xvideos_api/xvideos_api.py", line 319, in main
    video.download(quality=args.quality, path=path, downloader=args.downloader)
  File "/usr/local/lib/python3.10/dist-packages/xvideos_api/xvideos_api.py", line 169, in download
    Core().download(video=self, quality=quality, path=path, callback=callback, downloader=downloader)
  File "/usr/local/lib/python3.10/dist-packages/base_api/base.py", line 111, in download
    threaded_download(video=video, quality=quality, path=path, callback=callback)
  File "/usr/local/lib/python3.10/dist-packages/base_api/modules/download.py", line 72, in wrapper
    with open(path, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'milf_and_step_son_school_art_project_4k_mandy_flores.mp4/MILF and Step Son School Art Project 4K Mandy Flores.mp4'
```

best regards

**Comment by sugizo** [comment]
tested work and got the same result
```
!xvideos_api \
    --download 'https://www.xvideos.com/video.kkeilcbaf66/milf_and_step_son_school_art_project_4k_mandy_flores' \
    --quality 'best' \
    --downloader 'threaded' \
    --use-title True \
    --output './' 
```

and
```
!xvideos_api \
    --download 'https://www.xvideos.com/video.kkeilcbaf66/milf_and_step_son_school_art_project_4k_mandy_flores' \
    --quality 'best' \
    --downloader 'threaded' \
    --use-title False \
    --output './' 
```

**moral of tested above**
output must be directory path 
not 
file name (it's different from previous version that output must contain file name)
but 
still accepted

thanks and best regards
